### PR TITLE
Added transactional = false to GsonService

### PR DESCRIPTION
**Pull request by sindhurpillai**
Added transactional = false to GsonService.
Grails was adding a transaction to serialize and deserialize methods.

### CODE REVIEW

**Comment by sindhurpillai** [comment]
Hi,
We are dependent on this fix for the TPS issue in our production. Please approve the merge if the change looks good.

Thanks,
Sindhu

**Comment by rpalcolea** [comment]
Hi! 

I'll merge and deploy in a 30 min or less!

**Comment by rpalcolea** [comment]
Hi @sindhurpillai 

Version `1.2.5` is published and available: https://twitter.com/grailsplugins/status/773194692678877184

**Comment by sindhurpillai** [comment]
Thanks :+1:

**Pull request merged**
